### PR TITLE
Try to fix failing authorization test

### PR DESCRIPTION
**Pull request by alenkacz**
Tests for unauthorized docker push are failing and I don't think it is affected by my changes - maybe just the message changed

### CODE REVIEW

**Comment by alenkacz** [comment]
@shekhargulati any idea why various tests are failing? :( also it seems that I don't have access to artifacts which makes debugging even harder

**Comment by shekhargulati** [comment]
@alenkacz I have fixed the test case and merged your pull requests. Thanks for the help. Would you be interested to collaborate on 0.3.0 version of rx-docker-client? I am planning to upgrade library to latest Docker API version i.e. 1.23

**Comment by alenkacz** [comment]
@shekhargulati sure, why not ... I want to play with RxJava a bit anyway :)

**Comment by alenkacz** [comment]
@shekhargulati are there any issues already for this release? Because as I see, almost all current issues are already assigned to you...

**Comment by shekhargulati** [comment]
@alenkacz you can pick any of those. I cleanup issues today and add them to new release.

**Pull request merged**
